version: '3'

services:
  node:
    container_name: insignia_node
    image: node:20
    user: 1000:1000
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229
      - 5555:5555
    networks:
      - insignia

  mysql:
    container_name: insignia_mysql
    image: mysql:8.3
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    networks:
      - insignia

networks:
  insignia:
    name: insignia
