import './global.css';

export const metadata = {
  title: 'Welcome to Social Network',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        {children}
        <div id="portal"></div>
      </body>
    </html>
  );
}
